apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-processor
  namespace: kafka-stream-assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-processor
  template:
    metadata:
      labels:
        app: stream-processor
    spec:
      containers:
        - name: stream-processor
          image: kafka-stream-processor:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: INPUT_TOPIC
              value: "input-topic"
            - name: OUTPUT_TOPIC
              value: "output-topic"
            - name: GROUP_ID
              value: "stream-processor-group"
