apiVersion: v1
kind: Service
metadata:
  name: stream-processor-service
  namespace: kafka-stream-assessment
spec:
  selector:
    app: stream-processor
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
